package:
  name: eigen
  version: 3.2.2

source:
  fn: 3.2.2.tar.bz2
  url: http://bitbucket.org/eigen/eigen/get/3.2.2.tar.bz2


requirements:
  build:
    - cmake [win]
  
about:
  home: http://assimp.sourceforge.net/
  license: BSD
